### ISSUE TITLE
gpdk045 layout tech file

### ISSUE THREAD

**Issue by gdutee** [ucb-art/gpdk045#1]
Hi, 
seems to me, the gpdk045 template setup file for layout is missing

, lib_name, params, used_names, **kwargs)
    354 
    355         tech_params = self.grid.tech_info.tech_params
--> 356         self._tech_cls = tech_params['layout']['mos_tech_class']  # type: MOSTech
    357 
    358         # initialize parameters

KeyError: 'mos_tech_class'

**Comment by pkerichang** [comment]
Hello,

this repository is used in teaching a course and the layout side of the framework is not used.  There are no plans to support this feature in the near future.

If you're interested to learn more about layout with BAG please see https://github.com/ucb-art/BAG2_cds_ff_mpt.git

**Comment by LareinaWang** [comment]
> Hello,
> 
> this repository is used in teaching a course and the layout side of the framework is not used. There are no plans to support this feature in the near future.
> 
> If you're interested to learn more about layout with BAG please see https://github.com/ucb-art/BAG2_cds_ff_mpt.git

so if we want to use this gpdk045 for our IC design , how should we modify the tech file?
